#!/usr/bin/env bash
#
# Everywhere we have a Cargo.lock checked into git, check that it's usable.
#
# This avoids doing a full `cargo check` which actually compiles the crates.
# Our needs are closer to `cargo verify-project`, but we do want to check
# the entire dependency tree without compiling anything.
#
# The approach we use now is to run `cargo tree --locked`, which catches
# missing dependencies relatively quickly.
#

set -eu

function usage() {
cat <<EOF
check_all_lockfiles: Check (or update) every Cargo.lock checked into git.

Usage:
  check_all_lockfiles [opts]

  -h / --help: print this message
EOF
}

if command -v gnu-getopt >/dev/null; then
    # If gnu-getopt is present, the platform getopt is unlikely to be good.
    GETOPT=gnu-getopt
else
    GETOPT=getopt
fi

set +e
options=$("$GETOPT" -oh --long help -- "$@")
status="$?"
set -e
if test "$status" != 0; then
    usage
    exit 1
fi

eval set -- "$options"
while true; do
    case "$1" in
	-h | --help)
	    usage
	    exit 0
	    ;;
	--)
	    shift
	    break
	    ;;
    esac
done


for subdir in $(git ls-files | sed -n 's/^/.\//;s/Cargo.lock$//p'); do
    echo
    echo "---- Checking $subdir"
    (cd "$subdir" && cargo tree --locked > /dev/null)
done
